#!/bin/bash

# ==============================================================================
# Enterprise Master Operations Tool v3.0 (All-in-One Full Code)
# ==============================================================================

# กำหนดตัวแปรสี
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# บังคับรันด้วยสิทธิ์ Root
if [ "$EUID" -ne 0 ]; then
  echo -e "${RED}[!] Please run as root (use sudo).${NC}"
  exit 1
fi

# ดักจับการกด Ctrl+C เพื่อให้ออกโปรแกรมอย่างสวยงาม
trap 'echo -e "\n${RED}[!] Operation cancelled by user. Exiting...${NC}"; exit 1' SIGINT

# ==============================================================================
# Functions (ไส้ในของแต่ละระบบ)
# ==============================================================================

func_setup_vm() {
    echo -e "${GREEN}[*] Executing VM Provisioning...${NC}"
    LOG_FILE="/var/log/setup-vm.log"
    echo "--- Starting VM Setup: $(date) ---" > "$LOG_FILE"
    
    echo -e "${CYAN} -> Setting timezone to Asia/Bangkok...${NC}"
    timedatectl set-timezone Asia/Bangkok >> "$LOG_FILE" 2>&1
    
    echo -e "${CYAN} -> Updating OS & Installing Essential Tools...${NC}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq >> "$LOG_FILE" 2>&1
    apt-get upgrade -y -qq >> "$LOG_FILE" 2>&1
    apt-get install -y curl wget git htop vim qemu-guest-agent net-tools sysstat -qq >> "$LOG_FILE" 2>&1
    
    echo -e "${CYAN} -> Applying SSH Hardening (Disable Root Login)...${NC}"
    sed -i 's/^#*PermitRootLogin.*/PermitRootLogin no/' /etc/ssh/sshd_config
    systemctl restart sshd >> "$LOG_FILE" 2>&1
    
    echo -e "${GREEN}[+] VM Provisioning completed! Actions logged to $LOG_FILE${NC}"
    read -p "Press [Enter] to return to menu..."
}

func_install_snmp() {
    echo -e "${GREEN}[*] Installing & Configuring SNMP...${NC}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq && apt-get install -y snmpd snmp -qq
    
    echo ""
    read -p "Enter desired SNMP Community String [default: public]: " SNMP_COMMUNITY
    SNMP_COMMUNITY=${SNMP_COMMUNITY:-public}
    
    echo -e "${CYAN} -> Configuring SNMP with View-Based Access Control (VACM)...${NC}"
    cp /etc/snmp/snmpd.conf /etc/snmp/snmpd.conf.bak
    cat <<EOF > /etc/snmp/snmpd.conf
# Secure SNMP Configuration generated by Automation Tool
agentAddress udp:161,udp6:[::1]:161
view   all         included   .1
rocommunity $SNMP_COMMUNITY default -V all
sysLocation "Enterprise Datacenter"
sysContact "Admin"
EOF
    systemctl restart snmpd
    systemctl enable snmpd
    
    echo -e "${CYAN} -> Testing SNMP Local OID verification...${NC}"
    snmpwalk -v2c -c "$SNMP_COMMUNITY" 127.0.0.1 system | head -n 3
    
    echo -e "${GREEN}[+] SNMP setup completed and verified!${NC}"
    read -p "Press [Enter] to return to menu..."
}

func_install_zabbix() {
    echo -e "${GREEN}[*] Installing Zabbix Agent...${NC}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq && apt-get install -y zabbix-agent -qq
    
    echo ""
    read -p "Enter Zabbix Server IP or Hostname: " ZBX_SERVER
    read -p "Enter this server's Hostname (for Zabbix Web): " ZBX_HOST
    
    echo -e "${CYAN} -> Updating zabbix_agentd.conf...${NC}"
    sed -i "s/^Server=.*/Server=${ZBX_SERVER}/" /etc/zabbix/zabbix_agentd.conf
    sed -i "s/^ServerActive=.*/ServerActive=${ZBX_SERVER}/" /etc/zabbix/zabbix_agentd.conf
    sed -i "s/^Hostname=.*/Hostname=${ZBX_HOST}/" /etc/zabbix/zabbix_agentd.conf
    
    systemctl restart zabbix-agent
    systemctl enable zabbix-agent
    
    echo -e "${GREEN}[+] Zabbix Agent installed and pointing to $ZBX_SERVER!${NC}"
    read -p "Press [Enter] to return to menu..."
}

func_scan_malware() {
    echo -e "${GREEN}[*] Running System Malware Scan (chkrootkit/rkhunter)...${NC}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -qq && apt-get install -y rkhunter -qq
    
    echo -e "${CYAN} -> Updating properties...${NC}"
    rkhunter --propupd > /dev/null 2>&1
    
    echo -e "${CYAN} -> Scanning system (Warnings only)...${NC}"
    rkhunter --checkall --skip-keypress | grep -i warning
    
    echo -e "${GREEN}[+] Malware scan finished. Full report at /var/log/rkhunter.log${NC}"
    read -p "Press [Enter] to return to menu..."
}

func_preflight_check() {
    echo -e "${GREEN}[*] Running Cluster/Node Pre-Flight Check...${NC}"
    
    echo -e "\n${YELLOW}[ Network Interfaces & Bridge ]${NC}"
    ip -br a
    
    echo -e "\n${YELLOW}[ Disk Usage & Mounts ]${NC}"
    df -Th | grep -v loop
    
    echo -e "\n${YELLOW}[ System Load & Memory ]${NC}"
    free -m
    uptime
    
    echo -e "\n${YELLOW}[ QEMU Guest Agent Status ]${NC}"
    if systemctl is-active --quiet qemu-guest-agent; then
        echo -e "qemu-guest-agent is ${GREEN}RUNNING${NC}"
    else
        echo -e "qemu-guest-agent is ${RED}NOT RUNNING${NC}"
    fi
    
    echo -e "\n${GREEN}[+] Pre-flight check completed.${NC}"
    read -p "Press [Enter] to return to menu..."
}

func_system_update() {
    echo -e "${GREEN}[*] Running System Update & Cleanup...${NC}"
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get upgrade -y
    apt-get autoremove -y
    apt-get clean
    echo -e "${GREEN}[+] System is up to date and clean!${NC}"
    read -p "Press [Enter] to return to menu..."
}

# ==============================================================================
# Main Menu Logic
# ==============================================================================

show_menu() {
    clear
    echo -e "${CYAN}======================================================${NC}"
    echo -e "${GREEN}      Enterprise Master Operations Tool v3.0          ${NC}"
    echo -e "${CYAN}======================================================${NC}"
    echo -e "${YELLOW} [ Provisioning & Monitoring ]${NC}"
    echo "  1) VM Provisioning (Setup-VM / Hardening)"
    echo "  2) Install & Config SNMP (with VACM & Test)"
    echo "  3) Install Zabbix Agent"
    echo ""
    echo -e "${YELLOW} [ Security & Audit ]${NC}"
    echo "  4) Run Auto Scan Malware (rkhunter)"
    echo ""
    echo -e "${YELLOW} [ Infrastructure & Delivery ]${NC}"
    echo "  5) Cluster Delivery Pre-Flight Check"
    echo ""
    echo -e "${YELLOW} [ Maintenance ]${NC}"
    echo "  6) System Update & Cleanup"
    echo ""
    echo "  0) Exit"
    echo -e "${CYAN}======================================================${NC}"
}

while true; do
    show_menu
    read -p "Select an option [0-6]: " choice
    echo ""
    case $choice in
        1) func_setup_vm ;;
        2) func_install_snmp ;;
        3) func_install_zabbix ;;
        4) func_scan_malware ;;
        5) func_preflight_check ;;
        6) func_system_update ;;
        0) echo -e "${GREEN}Exiting gracefully. Goodbye!${NC}"; exit 0 ;;
        *) echo -e "${RED}[!] Invalid option. Please try again.${NC}"; sleep 1.5 ;;
    esac
done
